### ISSUE TITLE
"database is locked" appearing upon loading a model in

### ISSUE THREAD

**Issue by GonzaloQSystra** [iTwin/itwin-unreal-plugin#22]
LogCesium: Error: [2024-09-30 09:25:14.243] [error] [SqliteCache.cpp:475] database is locked
LogITwinCesium: Error: [2024-09-30 09:25:14.243] [error] [SqliteCache.cpp:609] database is locked

As per the attached image, when loading in a model this error shows up many times over until it stops. 
This does not necessarily stop the general compiling from happening, but it slows down the build and potentially gives 4D Timeline errors individually from load to load

<img width="1231" alt="Annotation 2024-09-30 092714" src="https://github.com/user-attachments/assets/18550843-5c38-4f07-ba5b-02c5b737392f">

**Comment by Julot94** [comment]
Hello @GonzaloQSystra 
This problem is almost certainly caused by the fact you are using both the _ITwin-Unreal_ plugin and the official _Cesium for Unreal_ plugin: they both try to access the same Cesium cache (located in %localappdata%/UnrealEngine/5.3/cesium-request-cache.sqlite). This has never been a problem in our tests, but accordingly to the logs you get here, it seems to be forbidden in your current installation.
As a workaround (until we make a change to use a separate database cache), you could avoid using the 2 plugins together. As stated in our documentation, you can perfectly load an "external" tileset (ie. non-iModels, like tileset coming from Cesium Ion server) using our plugin, by following these steps:

- Drag and drop an **ITwinCesium3DTileset** actor from the Content Browser into your level.
  This actor can be found in the content browser inside folder **Plugins/iTwin for Unreal C++ Classes/ITwinCesiumRuntime/Public.**

- In the actor's Details panel, in the **Cesium** section, fill the **Source**, _Url_, _Ion Asset ID_, _Ion Access token_ fields depending on the source of your tileset.

**Comment by Julot94** [comment]
If the problem persists when using only one of the plugins, then I suggest you rename the file
%localappdata%/UnrealEngine/5.3/**cesium-request-cache.sqlite**

(it probably means it was locked by the system at some point, and never released, maybe due to a crash in a previous session...)
