### ISSUE TITLE
Appearance Profiles not Vanishing

### ISSUE THREAD

**Issue by GonzaloQSystra** [iTwin/itwin-unreal-plugin#23]
The 4D Timeline for visualizing changes the colour of the model appropriately according to when it's being deconstructed, but when it comes down to making it invisible, it does not turn it at the time its supposed to, or at all.

Below is how its looking like in SYNCHRO
![image](https://github.com/user-attachments/assets/0385130c-4070-4669-b714-0c5614b40178)

Here's how it appears with the plugin, the red element are supposed to have disappeared
![image](https://github.com/user-attachments/assets/9740a225-6c88-4f59-b993-64494b679c0a)

**Comment by GhisBntly** [comment]
Hello,
Thanks for the report, that's indeed a problem I noticed and fixed last week, to be included in the next public release (no ETA for this at the moment, sorry). You may also notice that "Remove" tasks as well as "Maintenance" and "Temporary" tasks with the "Simulate as Remove" flag set are not simulated properly. Finally, growth direction is inverted along Y axis :-o
This will all be fixed in next version - thanks for your patience!
Regards,

**Comment by MSeddonProicere** [comment]
Hi Gonzalo,

I have a question for you, if you don't reply thats okay. But, I've been struggling to find ways to expose the plugin so that I can create widgets to command the plugin at runtime like you have here, especially the slider. Would you mind telling/showing me how you managed to do it, however brief that may be? Everytime I tried my editor either crashed or changes did not take effect

Thanks so much,
Matthew.

**Comment by Tim4DConstruct** [comment]
Indeed i would like to know too how you did the UI with the slider, I can't find any information on this.

**Comment by GhisBntly** [comment]
Closing as the mentioned fixes were included in release 0.1.11 from October 4th.

**Comment by NimrodFriedmann** [comment]
[like]  Nimrod Friedmann reacted to your message:
________________________________
